SQL Command use in this project:---

1. Create a new database:-- Create database ATM;
2. Use the database :   --  Use ATM;
3. Create ATM table with all columns: This table holds the details of an ATM OBJECT..
CREATE TABLE ATM
(
    ATM_ID INTEGER NOT NULL AUTO_INCREMENT,
    ATM_NAME VARCHAR(255) NOT NULL,
    ATM_ADDRESS VARCHAR(1000) NOT NULL,
    ATM_PINCODE VARCHAR(255) NOT NULL,
    AVAILABLE_BALANCE INTEGER NOT NULL,
    NO_OF_FIVE_HUNDRED_AVAILABLE INTEGER NOT NULL,
    NO_OF_ONE_HUNDRED_AVAILABLE INTEGER NOT NULL,
    DAY_IN_AMOUNT_DEPOSITED INTEGER NOT NULL,
    AMOUNT_DEPOSIT_STATUS  VARCHAR(255) NOT NULL,
    LAST_ATM_DEPOSIT_DATE TIMESTAMP,
    PRIMARY KEY(ATM_ID)
);
4. Create Table ATM_TRANSACTION : This will hold all the transaction that are made in that ATM.
CREATE TABLE ATM_TRANSACTION
(
    ATM_TRANS_ID INTEGER NOT NULL AUTO_INCREMENT,
    ATM_ID  INTEGER NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    ACCOUNT_ID INTEGER,
    TRANSACTION_TYPE VARCHAR(200),
    AMOUNT INTEGER NOT NULL,
    CONSTRAINT ATM_TRANSACTION_PK PRIMARY KEY(ATM_TRANS_ID),
    CONSTRAINT ATM_TRANSACTION_FK1 FOREIGN KEY (ATM_ID) REFERENCES ATM(ATM_ID)
);


5.Create Customer with all columns
CREATE TABLE CUSTOMER
(
    CUSTOMER_ID INTEGER NOT NULL AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(500) NOT NULL,
    BANK_NAME VARCHAR(500) NOT NULL,
    CUSTOMER_ADDRESS VARCHAR(500) NOT NULL,
    CUSTOMER_PINCODE VARCHAR(20) NOT NULL,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY(CUSTOMER_ID)
);
6.Create Customer account table
 CREATE TABLE CUST_ACCOUNTS
 (
        ACCOUNT_ID INTEGER NOT NULL AUTO_INCREMENT,
        CUSTOMER_ID INTEGER NOT NULL,
        ACCOUNT_NUMBER VARCHAR(200) NOT NULL,
        ACCOUNT_TYPE VARCHAR(10) NOT NULL,
        AVAILABLE_BALANCE DOUBLE NOT NULL,
        CONSTRAINT CUST_ACCOUNTS_PK PRIMARY KEY(ACCOUNT_ID),
        CONSTRAINT CUST_ACCOUNTS_FK1 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
 );
7.Create Customer card table
 CREATE TABLE ACCOUNT_CARD
 (
    CARD_ID INTEGER NOT NULL AUTO_INCREMENT,
    ACCOUNT_ID INTEGER NOT NULL,
    CARD_NUMBER VARCHAR (2000) NOT NULL,
    CARD_PIN  INTEGER NOT NULL,
    CONSTRAINT ACCOUNT_CARD_PK PRIMARY KEY(CARD_ID),
    CONSTRAINT ACCOUNT_CARD_FK1 FOREIGN KEY (ACCOUNT_ID) REFERENCES CUST_ACCOUNTS(ACCOUNT_ID)
 );
8
CREATE TABLE CARD_TRANSACTION
(
TRANSACTION_ID INTEGER NOT NULL AUTO_INCREMENT,
CARD_ID INTEGER NOT NULL,
TRANSACTION_TYPE VARCHAR (2000) NOT NULL,
AMOUNT  INTEGER NOT NULL,
TRANSACTION_DATE DATE,
CONSTRAINT TRANSACTION_PK PRIMARY KEY(TRANSACTION_ID),
CONSTRAINT TRANSACTION_FK1 FOREIGN KEY (CARD_ID) REFERENCES ACCOUNT_CARD(CARD_ID)
);



