server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: atm-service
          uri: lb://atm-service
          predicates:
            - Path=/atm/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true