name: Spring-Boot CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven service Discovery
        run: mvn -B package --file Discovery/pom.xml
      - name: Build with Maven service GateWay
        run: mvn -B package --file GateWayService/pom.xml
      - name: Build with Maven service Customer ATM
        run: mvn -B package --file Customer_ATM/pom.xml
      - name: Build with Maven service Bank ATM
        run: mvn -B package --file Bank_ATM/pom.xml