name: Spring Boot Docker Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: docker.io
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build & push service Discovery to Docker..
        run: mvn package dockerfile:push --file Discovery/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.  DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & push service  GateWay API to Docker..
        run: mvn package dockerfile:push --file GateWayService/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & push service  Customer to Docker..
        run: mvn package dockerfile:push --file Customer_ATM/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & push service  Bank ATM to Docker..
        run: mvn package dockerfile:push --file BANK_ATM/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

